development:
  adapter: postgresql
  database: red_table_development
  host: localhost
  username: postgres
  password: postgres
  port: 5432

test:
  adapter: postgresql
  database: red_table_test
  host: localhost
  username: postgres
  password: postgres
  port: 5432

production:
  adapter: postgresql
  database: red_table_production
  host: localhost
  username: postgres
  password: postgres
  port: 5432
