defaults: &defaults
  hosts: 
    - localhost:27017

development:
  sessions:
    default:
      database: red_table_development
      <<: *defaults

test:
  sessions:
    default:
      database: red_table_test
      <<: *defaults
      options:
        consistency: :strong
        max_retries: 1
        retry_interval: 0

production:
  sessions:
    default:
      database: red_table_production
      uri: <%= ENV['MONGOHQ_URL'] %>
