production:
  sessions:
    default:
      database: red_table_production
      hosts:
        - 127.0.0.1:27017

development:
  sessions:
    default:
      database: red_table_development
      hosts:
        - 127.0.0.1:27017

test:
  sessions:
    default:
      database: red_table_test
      hosts:
        - 127.0.0.1:27017
      options:
        consistency: :strong
        max_retries: 1
        retry_interval: 0
